on:
  push:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    name: CI
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-18.04, macos-10.15]
    steps:
      - uses: actions/checkout@v2
      - uses: ./setup-beam
        with:
          otp-version: 24.0-rc3
          elixir-version: 1.11.4
          gleam-version: 0.14.2
      - run: elixir --version
      - run: gleam --version
